kind: Deployment
apiVersion: apps/v1
metadata: 
 name: mysql
 namespace: expense
labels: 
 app: mysql
 tier: db
 project: expense
spec: 
  replicas: 1
  selector:
    matchLabels:
     app: nginx
  template:
   metadata: 
    labels: 
     app: mysql
     tier: db
     project: expense
   spec: 
    containers: 
    - name: mysql
      image: madhupitchapati/mysql:v1
      ports: 
      - containerPort: 80
